version: '3.9'
services: 

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    ports:
      - 81:80
    restart: always
    volumes:
      - .:/var/www/html/
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: db_mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=facil_solucoes
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=devadmin
      - MYSQL_ROOT_PASSWORD=root